### PR TITLE
[AS2-91] middleman and dependencies update

### PR DESCRIPTION
**Pull request by matheusdealencar**
PR - middleman and dependencies update
Jira Task: https://bitsomx.atlassian.net/browse/AS2-91

## Changes/solution

In order to deploy this API into https://bitsoex.github.io/slate/, it is required to run deploy-sh file, as described in [this](https://bitsomx.atlassian.net/wiki/spaces/API/pages/1403552200/Deployment+of+Slate+API+Docs) document.
Currently, it is not being possible to build and deploy files, because the middleman version is outdated. 
In order to build and deploy it successfully, this PR updates all dependencies and files related with middleman v.4.3.x version.

This PR contains the following features:
- middleman and dependencies version update, javascript, css and layout files update 

## Notes and considerations

- The previous layout was ready for slate version previous to v.1.5 (it uses middleman v.4.2.x, which does not work for deployment anymore), but, from v2.0 onwards, the whole layout construction has changed for slate. So, in order to update middleman's version, I also needed to update some javascript, css and layout files. I made those versions and files up to date with the following slate version: https://github.com/slatedocs/slate/releases/tag/v2.10.0

- I tried to run build as it was before, but then I got this error:
 
image

- I also tried to remove Gemfile.lock and run the build again, this time the build was completed, but the deploy execution was throwing this error:

image

(with verbose option):

image

### CODE REVIEW

**Review by joehorsnell — COMMENTED** [review]
Hi @matheusdealencar, quick question for you - how much of this PR is just pulling in changes from upstream and how much is stuff you've modified? It's obviously not straightforward to review PR with nearly 14k lines changed! If there is stuff that was pulled from upstream, it would probably make sense to put that in separately.

FYI, @thenewversion got assigned to review it but is not familiar with the toolchain here so asked if I could take a quick look.

**Comment by matheusdealencar** [comment]
> Hi @matheusdealencar, quick question for you - how much of this PR is just pulling in changes from upstream and how much is stuff you've modified? It's obviously not straightforward to review PR with nearly 14k lines changed! If there is stuff that was pulled from upstream, it would probably make sense to put that in separately.
> 
> FYI, @thenewversion got assigned to review it but is not familiar with the toolchain here so asked if I could take a quick look.

Hi Joe, most files are pulled from [upstream](https://github.com/slatedocs/slate/releases/tag/v2.10.0) (all except CHANGELOG.md and index.html.md, but those two are just revision updates as consequence of the pull). If it makes easier for you, I can separate it in two PRs. The first PR would have all the other files, and the second would have CHANGELOG.md and index.html.md updates

**Comment by joehorsnell** [comment]
> Hi Joe, most files are pulled from [here](https://github.com/slatedocs/slate/releases/tag/v2.10.0) (all except CHANGELOG.md and index.html.md, but those two are just revision updates as consequence of the pull). If it makes easier for you, I can separate it in two PRs. The first PR would have all the other files, and the second would have CHANGELOG.md and index.html.md updates

Hi @matheusdealencar - I definitely think it makes sense to always separate out changes that are just pulled from upstream from things you've done 👍

**Comment by matheusdealencar** [comment]
I have split this PR on two:
https://github.com/bitsoex/slate/pull/105
https://github.com/bitsoex/slate/pull/106

I'm closing this one. 
@joehorsnell @viccomx @thenewversion

**Pull request closed without merging**
