### PR TITLE
add new error code/description

### PR DESCRIPTION
**Pull request by julyanserra**
Add error code for: https://github.com/bitsoex/bitsoex/pull/4015

### CODE REVIEW

**Review by thenewversion — APPROVED** [review]

**Comment by julyanserra** [comment]
> Error codes seems fine but api code seems very wrong - [bitsoex/bitsoex#4015](https://github.com/bitsoex/bitsoex/pull/4015)

I think there is an **important** difference between something being wrong, and something not improving the existing functionality. I'll answer your comments in the old PR.

**Comment by julyanserra** [comment]
@viccomx checking in here

**Comment by viccomx** [comment]
@mrduckieduck / @lagonzalezr / @aitmanga is this still needed?

**Comment by mrduckieduck** [comment]
> @mrduckieduck / @lagonzalezr / @aitmanga is this still needed?
@viccomx  the related [PR](https://github.com/bitsoex/bitsoex/pull/4015) is already merged, so yes, this is necessary ... I see you took that code and made some comments in that closed [PR](https://github.com/bitsoex/bitsoex/pull/4015) ... Let's close this one and retake the work with new PR's and taking into consideration those "very wrong" things you mentioned. Can you help us creating a ticket?

**Pull request closed without merging**
